#.SILENT:#静默模式，不会输出执行的命令

include build.common.mk
include build.elf.mk
include lldb.mk
include lifecycle.mk
include aslr.mk
include bin.log.mk
include disassembly.mk
include requires.process.mk
include adoc.mk
